### ISSUE TITLE
Swift Package Manager (SPM) Support?

### ISSUE THREAD

**Issue by Vincent-Loi** [contentful-labs/rich-text-renderer.swift#10]
Hi, 

[Documentation](https://github.com/contentful-labs/rich-text-renderer.swift) states it supports SPM, but there isn't a Package.swift manifest file?

<img width="725" alt="Screenshot 2020-06-24 at 4 11 09 pm" src="https://user-images.githubusercontent.com/17518173/85582540-6c9d6e00-b635-11ea-992d-9bf4ba0e207e.png">

**Comment by tomkowz** [comment]
Thanks for the report @Vincent-Loi. The issue will be fixed in the next minor release.
