### ISSUE TITLE
Update podspec

### ISSUE THREAD

**Issue by timqzm** [contentful-labs/rich-text-renderer.swift#5]
Is it possible to update `spec.dependency 'Contentful', '~> 4.1.3'` to 5.X.X?

**Comment by timqzm** [comment]
I dealt it in my forks somehow ([here](https://github.com/timqzm/rich-text-renderer.swift/commit/74a3580385cd34415995843b4ffac63cc6eb0567) and [here](https://github.com/timqzm/contentful.swift/commit/334d0694730a104702380418cbb89ea58b07d0a6)) but faced a problem with lack of `resolvedResource` (was removed from contentful.swift [here](https://github.com/contentful/contentful.swift/commit/ff3486f389f3beb24538469dff98b504a16ed150#diff-c8e29ccf2373893e83f8296641090934)).
I'm not sure it's correct way but it works 🙃

**Comment by tomkowz** [comment]
Hello, guys. You should be able to update the library to 0.2.0 and it works with the newest Contentful 5.2.0. However, and thanks for pointing that, I'll update the Podspec to explicitly have the Contentful dependency set to `~> 5.2.0`.

**Comment by tomkowz** [comment]
This is fixed on `0.2.1`. Closing it for now.
