### ISSUE TITLE
image isn't loaded properly

### ISSUE THREAD

**Issue by mysimonbrodowski** [contentful-labs/rich-text-renderer.swift#7]
I tried to load RichTextDocument in RichTextViewController but it doesn't load image occasionally.
Only the first image is loaded successfully every time.
Anyone experienced of it?

**Comment by tomkowz** [comment]
Thanks for the report. We're working on the next major release that would include fixes for image rendering. However, I didn't notice issues with loading several assets in a row. Does it still happen for you with the latest version available?

**Comment by tomkowz** [comment]
@mysimonbrodowski in version `0.2.0` the images should load properly.

**Comment by tomkowz** [comment]
Closing it for now as there is no update on the issue. Let's open it again if the problem still occurs on the newest lib.
