### ISSUE TITLE
SwiftUI support?

### ISSUE THREAD

**Issue by basememara** [contentful-labs/rich-text-renderer.swift#9]
Is there any plans on getting rich text supported in SwiftUI?

**Comment by tomkowz** [comment]
Currently there is no plans to support for the SwiftUI. We're working on the major update for the library but it will not include SwiftUI. Cheers!

**Comment by joe-pellegrino** [comment]
@basememara you can wrap the view controller like so
`

import UIKit
import SwiftUI
import Contentful
import ContentfulRichTextRenderer

//@Binding var id: String

final class MarkdownContentType: Resource, EntryDecodable, FieldKeysQueryable {
    static let contentTypeId = "markdownContentType"

    let sys: Sys
    let markdownBody: String
    let name: String

    public required init(from decoder: Decoder) throws {
        sys = try decoder.sys()
        let fields = try decoder.contentfulFieldsContainer(keyedBy: FieldKeys.self)
        markdownBody = try fields.decode(String.self, forKey: .markdownBody)
        name = try fields.decode(String.self, forKey: .name)
    }

    enum FieldKeys: String, CodingKey {
        case name, markdownBody
    }
}

final class digitalMarketing: Resource, EntryDecodable, FieldKeysQueryable {
    
    static let contentTypeId = "digitalMarketing"

    let sys: Sys
    let name: String
    let body: RichTextDocument

    public required init(from decoder: Decoder) throws {
        sys = try decoder.sys()
        let fields = try decoder.contentfulFieldsContainer(keyedBy: FieldKeys.self)
        name = try fields.decode(String.self, forKey: .className)
        body = try fields.decode(RichTextDocument.self, forKey: .classText)
    }

    enum FieldKeys: String, CodingKey {
        case className, classText
    }
}

final class STTest: Resource, EntryDecodable, FieldKeysQueryable {
    
    static let contentTypeId = "stTest"

    let sys: Sys
    let name: String
    let body: RichTextDocument

    public required init(from decoder: Decoder) throws {
        sys = try decoder.sys()
        let fields = try decoder.contentfulFieldsContainer(keyedBy: FieldKeys.self)
        name = try fields.decode(String.self, forKey: .name)
        body = try fields.decode(RichTextDocument.self, forKey: .body)
    }

    enum FieldKeys: String, CodingKey {
        case name, body
    }
}

final class EmbeddedEntry: Resource, EntryDecodable, FieldKeysQueryable {

    static let contentTypeId = "embedded"

    let sys: Sys
    let body: String

    public required init(from decoder: Decoder) throws {
        sys = try decoder.sys()
        let fields = try decoder.contentfulFieldsContainer(keyedBy: FieldKeys.self)
        body = try fields.decode(String.self, forKey: .body)
    }

    enum FieldKeys: String, CodingKey {
        case body
    }
}

class EmbeddedTextView: UITextView, ResourceLinkBlockRepresentable {
    var surroundingTextShouldWrap: Bool = true
    var context: [CodingUserInfoKey: Any] = [:]

    func layout(with width: CGFloat) {
        frame.size = sizeThatFits(CGSize(width: width, height: .greatestFiniteMagnitude))
    }
}

struct MyInlineProvider: InlineProvider {
    func string(for resource: FlatResource, context: [CodingUserInfoKey: Any]) -> NSMutableAttributedString {
        if let embedded = resource as? EmbeddedEntry {
            let url = URL(string: "https://example.com/\(embedded.id)")!
            return NSMutableAttributedString(string: embedded.body, attributes: [.link: url])
        } else if let asset = resource as? Asset, let title = asset.title, let url = asset.url {
            return NSMutableAttributedString(string: title, attributes: [.link: url])
        }
        return NSMutableAttributedString(string: "")
    }
}

struct MyViewProvider: ViewProvider {
    func view(for resource: FlatResource, context: [CodingUserInfoKey: Any]) -> ResourceBlockView {
        if let embedded = resource as? EmbeddedEntry {
            let view = EmbeddedTextView(frame: .zero)
            view.context = context

            view.surroundingTextShouldWrap = false

            view.backgroundColor = .gray
            view.textColor = .black
            view.text = embedded.body

            view.sizeToFit()
            return view
        } else if let markdownType = resource as? MarkdownContentType {
            let view = EmbeddedTextView(frame: .zero)
            view.context = context

            let listContext = context[.listContext] as! ListContext
            view.surroundingTextShouldWrap = listContext.level == 0

            view.backgroundColor = .gray
            view.textColor = .black
            view.text = markdownType.markdownBody

            view.sizeToFit()
            return view
        } else if let asset = resource as? Asset, asset.file?.details?.imageInfo != nil {
            let imageView = EmbeddedAssetImageView(asset: asset)
            let listContext = context[.listContext] as! ListContext
            imageView.surroundingTextShouldWrap = listContext.level == 0
            imageView.backgroundColor = .gray
            imageView.setImageToNaturalHeight()
            return imageView
        }
        return EmptyView(frame: .zero)
    }
}


class ContentfulRTViewController: RichTextViewController {

    init() {
        var styling = RenderingConfiguration()
        styling.viewProvider = MyViewProvider()
        styling.inlineResourceProvider = MyInlineProvider()
        let renderer = DefaultRichTextRenderer(styleConfig: styling)
        super.init(richText: nil, renderer: renderer, nibName: nil, bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    let client = Client(spaceId: "SPACE-ID",
                        accessToken: "ACCESS-TOKEN",
                        contentTypeClasses: [digitalMarketing.self, EmbeddedEntry.self, MarkdownContentType.self])

    override func viewDidLoad() {
        super.viewDidLoad()

        view.backgroundColor = UIColor.white

        let query = QueryOn<digitalMarketing>.where(sys: .id, .equals("CONTENT-ID"))
        client.fetchArray(of: digitalMarketing.self,
                          matching: query) { [unowned self] result in
            switch result {
            case .success(let arrayResponse):
                self.richText = arrayResponse.items.first!.body

            case .error(let error):
                print("\(error)")
            }
        }
    }
}

struct ViewControllerWrapper: UIViewControllerRepresentable {

    typealias UIViewControllerType = ContentfulRTViewController


    func makeUIViewController(context: UIViewControllerRepresentableContext<ViewControllerWrapper>) -> ViewControllerWrapper.UIViewControllerType {
        return ContentfulRTViewController()
    }

    func updateUIViewController(_ uiViewController: ViewControllerWrapper.UIViewControllerType, context: UIViewControllerRepresentableContext<ViewControllerWrapper>) {
        //
    }
}
`
